### PR TITLE
Add SkiaSharp example project.

### PR DESCRIPTION
**Pull request by santoro-mariano**

### CODE REVIEW

**Comment by ForeverZer0** [comment]
Need to get a Windows VM installed, will merge soon.
Your contributions are most appreciated.

**Comment by santoro-mariano** [comment]
I added support to other platforms (MacOS and Linux) in the Skia example but I commented the code when it calls native methods in GLFW.NET to obtain specific platform contexts because that isn't implemented yet (it's has only been implemented for WGL and EGL contexts). Once those methods are wrapped, the example "should" work.
More specifically, the methods that the example needs to be wrapped in GLFW.NET are:
- [GLXContext glfwGetGLXContext(GLFWwindow * window)](https://www.glfw.org/docs/latest/group__native.html#ga62d884114b0abfcdc2930e89f20867e2)
- [id glfwGetNSGLContext( GLFWwindow * window)](https://www.glfw.org/docs/latest/group__native.html#ga559e002e3cd63c979881770cd4dc63bc)

**Comment by ForeverZer0** [comment]
I was unaware I even missed those functions, created an issue, will get it them added very soon (should be within next 8 hours), and will merge this once they are committed. #14

**Comment by ForeverZer0** [comment]
Pushed the required methods.
There are still a few native functions I am working on, though none that are required for the example project.

**Comment by ForeverZer0** [comment]
Working good on Linux.

**Comment by santoro-mariano** [comment]
Awesome! I didn't test it on OSX. I'll try it in the next few days.

**Comment by ForeverZer0** [comment]
That would be great, I always seem to trouble getting OSX VM's working correctly. :/

**Pull request merged**
